import { Product } from "../types/Products";

export const Products: Product[] = [
  {
    id: 1,
    name: "Nike Air Zoom Pegasus 39",
    price: 120.0,
    description:
      "Nike Air Zoom Pegasus 39 running shoes, lightweight design with Zoom Air cushioning.",
    imageUrl: ["http://example.com/nike-air-zoom-pegasus39.jpg"],
    category: "Running Shoes",
    stock: 100,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 180,
    rating: 4.7,
  },
  {
    id: 2,
    name: "Adidas Ultraboost 22",
    price: 180.0,
    description:
      "Adidas Ultraboost 22, featuring Boost cushioning for supreme comfort and energy return.",
    imageUrl: ["http://example.com/adidas-ultraboost22.jpg"],
    category: "Running Shoes",
    stock: 120,
    tags: ["new"],
    discount: 15,
    numberOfReviews: 220,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Puma RS-X3 Puzzle",
    price: 110.0,
    description:
      "Puma RS-X3 Puzzle, designed with EVA cushioning and a bold streetwear style.",
    imageUrl: ["http://example.com/puma-rsx3-puzzle.jpg"],
    category: "Lifestyle Shoes",
    stock: 80,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 150,
    rating: 4.5,
  },
  {
    id: 4,
    name: "Under Armour HOVR Phantom 2",
    price: 140.0,
    description:
      "Under Armour HOVR Phantom 2 running shoes, featuring HOVR technology for optimal foot support.",
    imageUrl: ["http://example.com/under-armour-hovr-phantom2.jpg"],
    category: "Running Shoes",
    stock: 90,
    tags: ["new"],
    discount: 12,
    numberOfReviews: 200,
    rating: 4.6,
  },
  {
    id: 5,
    name: "New Balance Fresh Foam 1080v11",
    price: 130.0,
    description:
      "New Balance Fresh Foam 1080v11, providing maximum cushioning and a smooth running experience.",
    imageUrl: ["http://example.com/new-balance-fresh-foam-1080v11.jpg"],
    category: "Running Shoes",
    stock: 100,
    tags: ["new"],
    discount: 8,
    numberOfReviews: 180,
    rating: 4.7,
  },
  {
    id: 6,
    name: "Nike Air Max 270 React",
    price: 150.0,
    description:
      "Nike Air Max 270 React, stylish lifestyle sneakers with Air Max cushioning for all-day comfort.",
    imageUrl: ["http://example.com/nike-air-max-270-react.jpg"],
    category: "Lifestyle Shoes",
    stock: 110,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 220,
    rating: 4.6,
  },
  {
    id: 7,
    name: "Adidas NMD_R1",
    price: 130.0,
    description:
      "Adidas NMD_R1 sneakers, featuring Boost cushioning and a sleek, modern design.",
    imageUrl: ["http://example.com/adidas-nmd-r1.jpg"],
    category: "Lifestyle Shoes",
    stock: 85,
    tags: ["new"],
    discount: 5,
    numberOfReviews: 150,
    rating: 4.6,
  },
  {
    id: 8,
    name: "Reebok Nano X1",
    price: 120.0,
    description:
      "Reebok Nano X1, designed for performance with superior grip and stability.",
    imageUrl: ["http://example.com/reebok-nano-x1.jpg"],
    category: "Training Shoes",
    stock: 100,
    tags: ["new"],
    discount: 12,
    numberOfReviews: 200,
    rating: 4.7,
  },
  {
    id: 9,
    name: "Nike React Infinity Run Flyknit",
    price: 160.0,
    description:
      "Nike React Infinity Run Flyknit, engineered for long-distance running with cushioning and support.",
    imageUrl: ["http://example.com/nike-react-infinity-run.jpg"],
    category: "Running Shoes",
    stock: 95,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 190,
    rating: 4.8,
  },
  {
    id: 10,
    name: "Adidas EQT Support 93/17",
    price: 140.0,
    description:
      "Adidas EQT Support 93/17, a classic design with Boost cushioning and modern updates.",
    imageUrl: ["http://example.com/adidas-eqt-support-93.jpg"],
    category: "Lifestyle Shoes",
    stock: 110,
    tags: ["new"],
    discount: 15,
    numberOfReviews: 170,
    rating: 4.5,
  },
  {
    id: 11,
    name: "Puma Suede Classic XXI",
    price: 85.0,
    description:
      "Puma Suede Classic XXI, iconic design with a premium suede upper for style and comfort.",
    imageUrl: ["http://example.com/puma-suede-classic.jpg"],
    category: "Lifestyle Shoes",
    stock: 60,
    tags: ["new"],
    discount: 5,
    numberOfReviews: 140,
    rating: 4.6,
  },
  {
    id: 12,
    name: "New Balance 990v5",
    price: 175.0,
    description:
      "New Balance 990v5, premium cushioning and support for everyday wear.",
    imageUrl: ["http://example.com/new-balance-990v5.jpg"],
    category: "Running Shoes",
    stock: 90,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 200,
    rating: 4.8,
  },
  {
    id: 13,
    name: "Nike ZoomX Vaporfly NEXT%",
    price: 250.0,
    description:
      "Nike ZoomX Vaporfly NEXT%, designed for speed with ultra-lightweight and responsive cushioning.",
    imageUrl: ["http://example.com/nike-zoomx-vaporfly.jpg"],
    category: "Running Shoes",
    stock: 70,
    tags: ["new"],
    discount: 5,
    numberOfReviews: 220,
    rating: 4.9,
  },
  {
    id: 14,
    name: "Adidas Crazy BYW X",
    price: 150.0,
    description:
      "Adidas Crazy BYW X, basketball shoes with responsive cushioning and high performance.",
    imageUrl: ["http://example.com/adidas-crazy-byw-x.jpg"],
    category: "Basketball Shoes",
    stock: 80,
    tags: ["new"],
    discount: 15,
    numberOfReviews: 180,
    rating: 4.7,
  },
  {
    id: 15,
    name: "Asics Gel-Kayano 28",
    price: 160.0,
    description:
      "Asics Gel-Kayano 28, ideal for long-distance runners with Gel cushioning and stability features.",
    imageUrl: ["http://example.com/asics-gel-kayano-28.jpg"],
    category: "Running Shoes",
    stock: 75,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 170,
    rating: 4.6,
  },
  {
    id: 16,
    name: "Saucony Endorphin Speed 2",
    price: 180.0,
    description:
      "Saucony Endorphin Speed 2, responsive and comfortable running shoes with Speedroll technology.",
    imageUrl: ["http://example.com/saucony-endorphin-speed2.jpg"],
    category: "Running Shoes",
    stock: 60,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 190,
    rating: 4.7,
  },
  {
    id: 17,
    name: "Nike Air Force 1 '07",
    price: 100.0,
    description:
      "Nike Air Force 1 '07, classic sneakers with premium leather and cushioned sole.",
    imageUrl: ["http://example.com/nike-air-force-1.jpg"],
    category: "Lifestyle Shoes",
    stock: 100,
    tags: ["new"],
    discount: 12,
    numberOfReviews: 230,
    rating: 4.8,
  },
  {
    id: 18,
    name: "Adidas Solar Boost 3",
    price: 140.0,
    description:
      "Adidas Solar Boost 3, running shoes with Solar Propulsion Rail for enhanced stability.",
    imageUrl: ["http://example.com/adidas-solar-boost3.jpg"],
    category: "Running Shoes",
    stock: 90,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 180,
    rating: 4.7,
  },
  {
    id: 19,
    name: "Reebok Zig Kinetica II Edge",
    price: 130.0,
    description:
      "Reebok Zig Kinetica II Edge, lifestyle sneakers with ZigTech cushioning for comfort and style.",
    imageUrl: ["http://example.com/reebok-zig-kinetica.jpg"],
    category: "Lifestyle Shoes",
    stock: 80,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 160,
    rating: 4.6,
  },
  {
    id: 20,
    name: "Under Armour Curry One",
    price: 150.0,
    description:
      "Under Armour Curry One, basketball shoes designed for performance with excellent grip and cushioning.",
    imageUrl: ["http://example.com/under-armour-curry-one.jpg"],
    category: "Basketball Shoes",
    stock: 100,
    tags: ["new"],
    discount: 10,
    numberOfReviews: 200,
    rating: 4.7,
  },
];
